os:
  - ubuntu/trusty64
cassandra:
  - 2.0
  - 2.1
  - 2.2
  - 3.0
  - 3.4
env:
  CSHARP_VERSION:
    - mono
    - netcore
build:
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      # Define Cassandra runtime
      export CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION
      echo "==========setting cassandra version=========="

      if [ $CSHARP_VERSION = 'mono' ]; then
          echo "==========csharp verion mono=========="
          # Define alias for Nuget
          nuget() {
                mono /home/jenkins/nuget/NuGet.exe "$@"
          }
          export -f nuget
          # Install the required packages
          export EnableNuGetPackageRestore=true
          nuget restore src/Cassandra.sln
          nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
          # Compile the driver and test code
          xbuild /p:Configuration=Release /v:m /p:restorepackages=false src/Cassandra.sln
          # Run the tests
          echo "==========RUNNING FULL SUITE OF TESTS=========="
          mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe src/Cassandra.Tests/bin/Release/Cassandra.Tests.dll src/Cassandra.IntegrationTests/bin/Release/Cassandra.IntegrationTests.dll --where:cat=short --labels=All --result:"TestResult.xml;format=nunit2" --trace=Verbose

      else
          echo "==========csharp verion netcore=========="
          # Install the required packages
          dotnet restore

          # Run the tests
          echo "==========RUNNING FULL SUITE OF TESTS=========="
          cd src/Cassandra.Tests
          
          dotnet test -f netcoreapp1.0 --work=../../ --result:"TestResult.xml;format=nunit2" --trace=Verbose
      fi
  - nunit:
    - "TestResult.xml"
